name: .NET

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 7.0.x
    - name: Install dependencies
      run: dotnet restore
      working-directory: backend/ToDo
    - name: Restore dependencies
      run: dotnet restore
      working-directory: backend/ToDo
    - name: Build
      run: dotnet build --no-restore
      working-directory: backend/ToDo
    - name: Test
      run: dotnet test --no-build --verbosity normal
      working-directory: backend/ToDo
